/*
 * Room-backed regex filter entity for NagramXF.
 *
 * Mirrors AyuFilter.FilterModel: a regex pattern with case-sensitivity, reversed
 * semantics, enabled flag, and an optional dialogId. When dialogId is null the
 * filter is "shared" (applies to every chat unless excluded); otherwise it is a
 * chat-specific filter.
 *
 * The primary key is the UUID string generated by FilterModel.ensureId(); we keep
 * it as a String rather than UUID so Room can store it without a converter and so
 * existing JSON exports (which use the same string form) import unchanged.
 */

package com.radolyn.ayugram.database.entities;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.Index;
import androidx.room.PrimaryKey;

@Entity(
        tableName = "RegexFilter",
        indices = {
                @Index(value = "dialogId"),
                @Index(value = "enabled")
        }
)
public class RegexFilter {
    @PrimaryKey
    @NonNull
    public String id;
    public String text;
    public Long dialogId;
    public boolean enabled;
    public boolean caseInsensitive;
    public boolean reversed;
}
