pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        maven { url 'https://chaquo.com/maven-central' }
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

include ':TMessagesProj'

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

gradle.ext.androidxMediaModulePrefix = 'TMessagesProj_Modules:media3:media-'
apply from: file('media_settings.gradle')
